/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2016-03-22-3e650e4"
#endif /* AVUTIL_FFVERSION_H */
